"""Tests for chalk.canvas_export (F-03)."""

from html.parser import HTMLParser

from chalk import branding
from chalk.canvas_export import render_canvas_html, write_canvas_html
from chalk.metrics import read_events_by_type
from tests.sample_course import build_sample_course_data


class _TagCollector(HTMLParser):
    def __init__(self):
        super().__init__()
        self.tags: list[str] = []

    def handle_starttag(self, tag, attrs):
        self.tags.append(tag)


def _tags(html: str) -> list[str]:
    parser = _TagCollector()
    parser.feed(html)
    return parser.tags


def test_starts_with_header_comment_sourced_from_branding_constant(monkeypatch):
    monkeypatch.setattr(branding, "PROJECT_NAME", "Renamed")
    html = render_canvas_html(build_sample_course_data())
    assert html.startswith("<!-- Generated by Renamed — paste into Canvas HTML editor -->")


def test_uses_a_semantic_table_with_header_cells():
    tags = _tags(render_canvas_html(build_sample_course_data()))
    for tag in ("table", "caption", "thead", "tbody", "th", "td"):
        assert tag in tags


def test_has_no_script_style_or_external_links():
    html = render_canvas_html(build_sample_course_data())
    tags = _tags(html)
    assert "script" not in tags
    assert "style" not in tags
    assert "link" not in tags
    assert "http" not in html


def test_has_one_row_per_week_including_breaks():
    course_data = build_sample_course_data()
    html = render_canvas_html(course_data)
    # One header row plus one body row per week (10 regular + 1 break).
    assert html.count("<tr") == 1 + len(course_data.weeks)


def test_regular_week_row_lists_topics_and_assignments():
    html = render_canvas_html(build_sample_course_data())
    assert "Week 1" in html
    assert "Aug 24" in html
    assert "Topic 1A" in html and "Topic 1B" in html
    assert "Lab 1 Due" in html
    assert "Video Quizzes are Taken After Reading Each Chapter" in html


def test_break_row_spans_the_content_columns_and_shows_its_range():
    html = render_canvas_html(build_sample_course_data())
    assert "Fall Break" in html
    assert "Oct 10 – Oct 18" in html
    assert 'colspan="2"' in html


def test_rows_are_in_date_order():
    html = render_canvas_html(build_sample_course_data())
    assert html.index("Week 7") < html.index("Fall Break") < html.index("Week 8")


def test_escapes_html_special_characters_in_course_content():
    course_data = build_sample_course_data()
    first_week = course_data.weeks[0].model_copy(update={"topics": ["<b>Routers & Switches</b>"]})
    course_data = course_data.model_copy(update={"weeks": [first_week, *course_data.weeks[1:]]})

    html = render_canvas_html(course_data)

    assert "&lt;b&gt;Routers &amp; Switches&lt;/b&gt;" in html
    assert "<b>" not in html


def test_caption_names_the_course_and_term():
    html = render_canvas_html(build_sample_course_data())
    assert "IS 6640 Networking and Servers — Fall 2026 Schedule" in html


def test_write_creates_the_file_and_archives_the_previous_version(tmp_path):
    output_path = tmp_path / "outputs" / "canvas.html"
    log_path = tmp_path / "eval-log.json"
    course_data = build_sample_course_data()

    write_canvas_html(course_data, output_path, eval_log_path=log_path)
    write_canvas_html(course_data, output_path, eval_log_path=log_path)

    assert output_path.read_text(encoding="utf-8") == render_canvas_html(course_data)
    assert len(list((output_path.parent / ".archive").iterdir())) == 1
    assert len(read_events_by_type(log_path, "archive")) == 1


def test_break_rows_do_not_repeat_the_dates_embedded_in_their_label():
    course_data = build_sample_course_data()
    weeks = [
        w.model_copy(update={"label": "Fall Break (10/10 - 10/18)"}) if w.is_break else w
        for w in course_data.weeks
    ]
    html = render_canvas_html(course_data.model_copy(update={"weeks": weeks}))
    assert "<strong>Fall Break</strong>" in html
    assert "10/10 - 10/18" not in html
