"""Canvas-paste schedule HTML (F-03).

Renders the course schedule from course.json as a single semantic HTML
table the instructor pastes into Canvas's HTML editor. Per PRD section
6.3: no external CSS, no JavaScript, minimal inline styles, schedule and
module content only (not the full syllabus).

The header comment's product name comes from chalk.branding at call time
— never a hardcoded literal (PLAN.md Risk #9).
"""

from __future__ import annotations

import datetime as dt
from html import escape
from pathlib import Path

from chalk import branding
from chalk.archiving import archive_before_write
from chalk.models import CourseData, Week
from chalk.rollover.preview import break_name

_TABLE_STYLE = "border-collapse: collapse; width: 100%;"
_CELL_STYLE = "border: 1px solid #c7cdd1; padding: 6px 8px; text-align: left; vertical-align: top;"
_COLUMNS = ("Week", "Dates", "Topics", "Assignments")


def render_canvas_html(course_data: CourseData) -> str:
    """Return the Canvas-paste HTML for `course_data`'s schedule."""
    course = course_data.course
    caption = f"{course.title} — {course.term} Schedule"
    header_cells = "".join(
        f'<th scope="col" style="{_CELL_STYLE}">{column}</th>' for column in _COLUMNS
    )
    body_rows = [_render_week_row(week) for week in sorted(course_data.weeks, key=_week_sort_key)]

    lines = [
        f"<!-- Generated by {branding.PROJECT_NAME} — paste into Canvas HTML editor -->",
        f'<table style="{_TABLE_STYLE}">',
        f"  <caption><strong>{escape(caption)}</strong></caption>",
        f"  <thead><tr>{header_cells}</tr></thead>",
        "  <tbody>",
        *(f"    {row}" for row in body_rows),
        "  </tbody>",
        "</table>",
    ]
    return "\n".join(lines) + "\n"


def write_canvas_html(course_data: CourseData, output_path, *, eval_log_path=None) -> Path:
    """Write the Canvas HTML to `output_path` (normally
    outputs/canvas.html), archiving any previous version first."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    archive_before_write(output_path, eval_log_path=eval_log_path)
    output_path.write_text(render_canvas_html(course_data), encoding="utf-8")
    return output_path


def _render_week_row(week: Week) -> str:
    if week.is_break:
        dates = f"{_short_date(week.date_start)} – {_short_date(week.date_end)}"
        return (
            f'<tr><th scope="row" style="{_CELL_STYLE}">—</th>'
            f'<td style="{_CELL_STYLE}">{dates}</td>'
            f'<td colspan="2" style="{_CELL_STYLE}"><strong>{escape(break_name(week.label))}</strong>'
            " — no class</td></tr>"
        )

    topics = _render_list(week.topics)
    if week.notes:
        topics += f"<p><em>{escape(week.notes)}</em></p>"
    return (
        f'<tr><th scope="row" style="{_CELL_STYLE}">Week {week.week_number}</th>'
        f'<td style="{_CELL_STYLE}">{_short_date(week.date)}</td>'
        f'<td style="{_CELL_STYLE}">{topics}</td>'
        f'<td style="{_CELL_STYLE}">{_render_list(week.assignments)}</td></tr>'
    )


def _render_list(items: list[str]) -> str:
    if not items:
        return ""
    return "<ul>" + "".join(f"<li>{escape(item)}</li>" for item in items) + "</ul>"


def _short_date(date: dt.date) -> str:
    return f"{date.strftime('%b')} {date.day}"


def _week_sort_key(week: Week) -> dt.date:
    return week.date if week.date is not None else week.date_start
